name: tests

on:
  push:
    branches: [ca7]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: environment-set-up
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # - name: build
      #   run: mvn compiler:testCompile
      - name: tests
        run: mvn test
      - name: bdd-tests
        run: mvn -Dtest="bdd.BDDEntryPointAcceptanceTest" test
